version: '3.8'

services:
  test-app:
    build:
      context: ./test_server
      dockerfile: Dockerfile
    networks:
      - app_network

  auth-server:
    build:
      context: ./auth_server
      dockerfile: Dockerfile
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=test
      - SESSION_LIFETIME=18 #in seconds
    networks:
      - app_network

  proxy:
    image: nginx
    volumes:
    - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']
    depends_on:
      - auth-server
      - test-app
    ports:
      - 8000:80
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
